name: example
description: A sample command-line application.
publish_to: none

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  json_annotation: ^4.0.1

  easy_enum: ^1.0.0

dev_dependencies:
  build_runner: ^2.0.0
  json_serializable: ^4.1.0
  
  easy_enum_generator:
    path: ../easy_enum_generator
    # git:
    #   url: https://github.com/faithoflifedev/easy_enum.git
    #   path: easy_enum_generator