name: example
description: A sample command-line application.
publish_to: none

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  json_annotation: ^4.0.1

  better_enum: ^1.0.0

dev_dependencies:
  build_runner: ^2.0.0
  json_serializable: ^4.1.0
  
  better_enum_generator:
    git:
      url: https://github.com/faithoflifedev/better_enum.git
      path: better_enum_generator