name: better_enum
description: Annotation for generating `BetterEnum` extensions code using `better_enum_generator`.
homepage: https://github.com/faithoflifedev/better_enum/tree/master/better_enum
repository: https://github.com/faithoflifedev/better_enum
issue_tracker: https://github.com/faithoflifedev/better_enum/issues

version: 1.0.0

environment:
  sdk: '>=2.12.0 <3.0.0'
