name: easy_enum
description: Annotation for generating `EasyEnum` extensions code using `easy_enum_generator`.
homepage: https://github.com/faithoflifedev/easy_enum/tree/master/easy_enum
repository: https://github.com/faithoflifedev/easy_enum
issue_tracker: https://github.com/faithoflifedev/easy_enum/issues

version: 1.0.0

environment:
  sdk: '>=2.12.0 <3.0.0'
