name: better_enum_generator
description: Automatically generating `copyWith` extensions code for classes with `@CopyWith()` annotation.
version: 1.0.0
homepage: https://github.com/faithoflifedev/better_enum/tree/master/better_enum_generator

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  analyzer: ^1.5.0
  json_serializable: ^4.1.0
  recase: ^4.0.0
  source_gen: ^1.0.0

  better_enum:
    path: ../better_enum
    
dev_dependencies:
  build_runner: ^2.0.0
