name: better_enum_generator
description: Automatically generating `BetterEnum` extensions code for classes with `@BetterEnum()` annotation.
homepage: https://github.com/faithoflifedev/better_enum/tree/main/better_enum_generator
repository: https://github.com/faithoflifedev/better_enum
issue_tracker: https://github.com/faithoflifedev/better_enum/issues

version: 1.0.0

publish_to: none

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  analyzer: ^1.5.0
  json_serializable: ^4.1.0
  recase: ^4.0.0
  source_gen: ^1.0.0

  better_enum:
    git:
      url: https://github.com/faithoflifedev/better_enum.git
      path: better_enum
    
dev_dependencies:
  build_runner: ^2.0.0
