builders:
  serializeGeneratorBuilder:
    import: 'package:easy_enum_generator/builder.dart'
    builder_factories: ['serializeGeneratorBuilder']
    auto_apply: dependents
    build_extensions: {".dart": [".enum.part"]}
    build_to: cache
    applies_builders: ["source_gen|combining_builder"]