name: easy_enum_generator
description: Automatically generating `EasyEnum` extensions code for classes with `@EasyEnum()` annotation.
homepage: https://github.com/faithoflifedev/easy_enum/tree/main/easy_enum_generator
repository: https://github.com/faithoflifedev/easy_enum
issue_tracker: https://github.com/faithoflifedev/easy_enum/issues

version: 2.0.1

environment:
  sdk: ">=2.13.0 <3.0.0"

dependencies:
  analyzer: ^2.7.0
  build: ^2.1.1
  json_serializable: ^6.0.1
  recase: ^4.0.0
  source_gen: ^1.1.1

  easy_enum: ^1.0.0

dev_dependencies:
  build_runner: ^2.1.4
